# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (every 3 hours)
  schedule: [{cron: "0 */3 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          filename: profile.svg
          user: Senexis
          template: classic
          base: header, activity, community, repositories, metadata
          config_display: columns
          config_octicon: yes
          config_timezone: Europe/Amsterdam
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          filename: languages.svg
          user: Senexis
          template: classic
          base: ""
          config_display: columns
          config_octicon: yes
          config_timezone: Europe/Amsterdam
          
          # Plugins
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          filename: achievements.svg
          user: Senexis
          template: classic
          base: ""
          config_display: columns
          config_octicon: yes
          config_timezone: Europe/Amsterdam
          
          # Plugins
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 12
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          filename: other.svg
          user: Senexis
          template: classic
          base: ""
          config_display: columns
          config_octicon: yes
          config_timezone: Europe/Amsterdam
          
          # Plugins
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_repositories_visibility: public
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
